apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
    traefik.enable: "true"
    traefik.http.middlewares.strip-counter.stripprefix.prefixes: /whoami
    traefik.http.routers.whoami.entrypoints: web
    traefik.http.routers.whoami.rule: Path(`/whoami`)
  creationTimestamp: null
  labels:
    io.kompose.service: whoami
  name: whoami
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: whoami
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
        traefik.enable: "true"
        traefik.http.middlewares.strip-counter.stripprefix.prefixes: /whoami
        traefik.http.routers.whoami.entrypoints: web
        traefik.http.routers.whoami.rule: Path(`/whoami`)
      creationTimestamp: null
      labels:
        io.kompose.service: whoami
    spec:
      containers:
        - image: traefik/whoami
          name: simple-service
          resources: {}
      restartPolicy: Always
status: {}
